imports:
    - { resource: config_dev.yml }

parameters:
    secret: TestSecret
    database_url: mysql://root@localhost/test_appname

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false
