imports:
    - { resource: config.yml }

framework:
    profiler: { only_exceptions: false }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: syslog
        syslog:
            type: syslogudp
            host: someotherhost.com
            port: 12345
            level: info
        console:
            type:  console
